linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused

run:
  deadline: 5m

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
